version: "3"

services:
  test_nsqlookupd:
    image: nsqio/nsq:v0.3.8
    command: /nsqlookupd
    ports:
      - "127.0.0.1:4160:4160"
      - "127.0.0.1:4161:4161"
  test_nsqd:
    image: nsqio/nsq:v0.3.8
    links:
      - test_nsqlookupd:test_nsqlookupd
    command: /nsqd --lookupd-tcp-address=test_nsqlookupd:4160 --broadcast-address=test_nsqd --tcp-address=test_nsqd:4150
    ports:
      - "127.0.0.1:4150:4150"
      - "127.0.0.1:4151:4151"
  test_nsqadmin:
    image: nsqio/nsq:v0.3.8
    links:
      - test_nsqlookupd:test_nsqlookupd
      - test_nsqd:test_nsqd
    command: /nsqadmin --lookupd-http-address=test_nsqlookupd:4161
    ports:
      - "127.0.0.1:4171:4171"